### PR TITLE
Provide each NSURLSession with a delegate queue

### PR DESCRIPTION
**Pull request by MrRooni**
## Reason to Be

Every `NSURLSession` in the `DBTransportDefaultClient` was sharing a single queue that was also used by the session delegate to enqueue responses. By giving each session its own delegate operation queue we reduce the risk that a response will be blocked by another session’s operations.

## Thought Process

While testing the download of a large number of files within 1Password I noticed this sharing of a single `NSOperationQueue` across multiple `NSURLSession`s. Since `NSURLSession`'s delegate queue must be a serial queue I was concerned about deadlocks sharing this one queue across multiple sessions as well as it being used as the response queue that the `NSURLSession`'s delegate instance uses.

Note that we did not actually witness any problems with the way the code was before, but this makes me feel a whole lot better. :smiley:

## How To Test

Ensure that you can build, run, and that the tests all pass.

## Possible Impacts

Unless there was some side effect given how this code was before, I can't think of any negative impact this change may have.

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks again Michael!

**Comment by MrRooni** [comment]
No problem @greg-db. Now if @scobbe turns around for a second time and tells me that _this_ work is also done, then I'm out! 😄

**Comment by scobbe** [comment]
Thanks Michael! Appreciate you taking the time to do this and help the SDK adhere to best practices!

**Comment by MrRooni** [comment]
No problem at all @scobbe. Cheers!

**Pull request merged**
