### PR TITLE
fix build error using the macOS SDK with Xcode 12.4

### PR DESCRIPTION
**Pull request by LGriffioen**
when building the latest macOS SDK, i'm getting this error:

Screen Shot 2021-06-17 at 8 49 28 AM

assuming that the `DBSDKImports-macOS.h` has all of the correct public headers, the proposed solution here is to change the `DBOAuthUtils.h` file from being a public header to a project header.

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks! For reference, can you also let me know what version of macOS you're running, and what method you're using to install and build the SDK?

I'll ask the team to look over this.

**Comment by LGriffioen** [comment]
sure! I'm using macOS 11.4 and the SDK is being pulled in as a git submodule and built as a dependent project in our workspace.

**Comment by greg-db** [comment]
Thanks! To clarify though, are you not using CocoaPods or Carthage?

**Comment by LGriffioen** [comment]
nope, just pure git submodule

**Comment by greg-db** [comment]
I see, thanks. I don't believe we've built and tested the SDK with that method in mind, but I'll ask the team to take a look.

**Comment by LGriffioen** [comment]
thanks for taking a look! fwiw we were previously on the 3.7.0 release tag and that had no issues (we should update more often :/)

**Pull request merged**
